# Generated by Django 5.0.8 on 2024-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id42",
            field=models.TextField(null=True),
        ),
    ]
