# Generated by Django 5.0.6 on 2024-08-28 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must be valid', regex='^[\\w.-]+@([\\w-]+\\.)+[a-zA-Z]{2,3}$')]),
        ),
    ]
