# Generated by Django 5.0.8 on 2024-10-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('fr', 'French'), ('zh', 'Simplified Chinese')], default='es', max_length=2),
        ),
    ]
