# Generated by Django 5.0.8 on 2024-10-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_friendship_user_friends'),
        ('user', '0010_user_is_verified'),
    ]

    operations = [
    ]
