# Generated by Django 5.0.8 on 2024-11-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_friendship_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.FileField(max_length=200, null=True, upload_to='profile_banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(max_length=200, null=True, upload_to='profile_images/'),
        ),
    ]
