name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "betta" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate SSH key
      run: |
        ssh-keygen -t rsa -b 2048 -m PEM -f "$JWT_PRIVATE_KEY_PATH" -N "$SUPER_SECRET" -q
      env:
        SUPER_SECRET: ${{ secrets.JWT_PRIVATE_KEY_PASSWORD }}
        JWT_PRIVATE_KEY_PATH: ${{ secrets.JWT_PRIVATE_KEY_PATH }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py migrate
        python manage.py test
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
        DJANGO_HTTPS: ${{ secrets.DJANGO_HTTPS }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        POSTGRES_DB: ${{ secrets.DB_NAME }}
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        JWT_PRIVATE_KEY_PATH: ${{ secrets.JWT_PRIVATE_KEY_PATH }}
        JWT_PUBLIC_KEY_PATH: ${{ secrets.JWT_PUBLIC_KEY_PATH }}
        JWT_PRIVATE_KEY_PASSWORD: ${{ secrets.JWT_PRIVATE_KEY_PASSWORD }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        OAUTH_UID: ${{ secrets.OAUTH_UID }}
        OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
        OAUTH_REDIRECT_URI: ${{ secrets.OATUH_REDIRECT_URI }}
