# Generated by Django 5.0.6 on 2024-06-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_user_id_statistics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='time_played',
            field=models.TimeField(default=None),
        ),
    ]
