# Generated by Django 5.0.8 on 2024-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_localmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localmatch',
            name='user_a',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='localmatch',
            name='user_b',
            field=models.CharField(null=True),
        ),
    ]
