# Generated by Django 5.0.8 on 2024-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_localmatch_user_a_alter_localmatch_user_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='num_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
