# Generated by Django 5.0.8 on 2024-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_tournament_localmatch_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localmatch',
            name='user_a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='localmatch',
            name='user_b',
            field=models.CharField(max_length=50),
        ),
    ]
